# Minimal, environment-friendly pre-commit configuration for RuleHub.
# This uses system-installed tools so it works in devcontainers and CI where
# the required binaries are available. Keep hooks fast and deterministic.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: '^(.github/workflows/.*\\.ya?ml|mkdocs\\.ya?ml|\\.pre-commit-config\\.ya?ml|policies/.*/metadata.yaml)$'
        args:
          - -d
          - |
            extends: default
            rules:
              indentation:
                spaces: 2
                indent-sequences: consistent
              line-length:
                max: 140
                level: warning
              truthy:
                allowed-values: ['true', 'false']
              trailing-spaces: enable
              document-start: disable

  # Local hooks for ruff and mypy are defined under the `local` repo below.

  - repo: local
    hooks:
      - id: ruff-local
        name: ruff (local)
        entry: bash -c 'command -v ruff >/dev/null 2>&1 && ruff check --exit-zero . || echo "ruff not found; skipping"'
        language: system
        types: [python]
        files: '^(.*/)?tools/.*\\.py$|^.*\\.py$'

      - id: mypy-local
        name: mypy (local)
        entry: bash -c 'command -v mypy >/dev/null 2>&1 && mypy --config-file mypy.ini "$@" || echo "mypy not found; skipping"'
        language: system
        types: [python]
        files: '^(.*/)?tools/.*\\.py$|^.*\\.py$'
      - id: opa-fmt-check
        name: OPA fmt verify (skip if opa missing)
        entry: bash -c 'if command -v opa >/dev/null 2>&1; then CHANGED=$(opa fmt -l policies || true); if [ -n "$CHANGED" ]; then echo "$CHANGED"; exit 1; fi; else echo "opa not found; skipping opa fmt check"; fi'
        language: system
        files: '^policies/.*\\.rego$'

      - id: validate-metadata
        name: Validate policy metadata (quick)
        entry: .venv/bin/python tools/validate_metadata.py
        language: system
        files: '^policies/.*/metadata.yaml$'

      - id: refs-index
        name: references index generate (fast)
        entry: .venv/bin/python tools/generate_refs_index.py --format both --fail-missing-links
        language: system
        pass_filenames: false
        files: '^policies/.*/metadata.yaml$'

      - id: markdownlint
        name: markdownlint (best-effort)
        entry: bash -c 'if command -v markdownlint-cli2 >/dev/null 2>&1; then markdownlint-cli2 "**/*.md"; else echo "markdownlint not found; skipping"; fi'
        language: system
        pass_filenames: false
        files: '\\.md$'

default_language_version:
  python: python3

ci:
  autofix_prs: false
  autoupdate_schedule: monthly
