title: "Idea: <brief summary>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Describe the idea / improvement. If possible include the problem and expected outcome.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What exactly do you propose?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Additional info, alternatives, links
