name: Resolve RuleHub CI image
description: Resolve GHCR image reference for RuleHub CI images (ci-base, ci-policy, ci-charts, ci-frontend) with a provided or fallback tag.

inputs:
  ci_image_tag:
    description: >-
      Immutable tag to use for the CI image (e.g., 2025.10.03-a1b2c3d4 or v1.2.3).
      If empty, falls back to repository/organization variable CI_IMAGE_TAG; if still empty, uses 'latest'.
    required: false
    default: ''
  kind:
    description: Which CI image kind to resolve (base|policy|charts|frontend)
    required: false
    default: base

outputs:
  image:
    description: Resolved image reference (e.g., ghcr.io/<owner>/ci-base:<tag>)
    value: ${{ steps.resolve.outputs.image }}
  tag:
    description: Resolved tag used for the image
    value: ${{ steps.resolve.outputs.tag }}

runs:
  using: composite
  steps:
    - id: resolve
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.ci_image_tag }}
        OWNER: ${{ github.repository_owner }}
        KIND: ${{ inputs.kind }}
      run: |
        set -euo pipefail
        kind="${KIND:-base}"
        case "$kind" in
          base|policy|charts|frontend) ;;
          *) echo "Unsupported kind: $kind (expected base|policy|charts|frontend)" >&2; exit 2;;
        esac

        ENV_TAG="${CI_IMAGE_TAG:-}"
        tag="${INPUT_TAG:-}"
        if [ -z "$tag" ] && [ -n "$ENV_TAG" ]; then
          tag="$ENV_TAG"
        fi
        if [ -z "$tag" ]; then tag="latest"; fi

        image="ghcr.io/${OWNER}/ci-${kind}:${tag}"

        echo "image=$image" >> "$GITHUB_OUTPUT"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"
