# yaml-language-server: $schema=../../../tools/schemas/policy-metadata.schema.json
id: k8s.no_run_as_root
name: Disallow running as root
standard: Kubernetes
version: 1.x
path:
- addons/k8s-gatekeeper/templates/no-run-as-root.yaml
- policies/k8s/no_run_as_root/policy.rego
- policies/k8s/no_run_as_root/policy_test.rego
description: Require containers to run as non-root users.
framework: gatekeeper
tags:
- k8s
- security
owner: platform-security
links:
- https://kubernetes.io/docs/concepts/security/pod-security-standards/
- https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
geo:
  regions:
  - Global
  countries:
  - '*'
  subregions: []
  scope: Global
