name: docs-publish

# Publishes MkDocs site to GitHub Pages.
# Triggers:
#  - Manual dispatch
#  - On published release (GitHub Release created by release-please or manually)
# Ensure mkdocs.yml `site_url` matches: https://<org_or_user>.github.io/<repo>/
on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-deploy:
    # Skip under act; publishing to Pages is CI-only
    if: ${{ github.actor != 'nektos/act' }}
    runs-on: ubuntu-latest
    concurrency:
      group: docs-publish
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-docs.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install MkDocs deps (pinned if available)
        run: |
          python -m pip install -U pip
          if [ -f requirements-docs.txt ]; then pip install -r requirements-docs.txt; else pip install mkdocs mkdocs-material; fi

      - name: Build site (strict)
        run: mkdocs build --strict --verbose

      - name: Validate site_url
        run: |
          URL_LINE=$(grep -E '^site_url:' mkdocs.yml || true)
          if [ -z "$URL_LINE" ]; then
            echo "::warning::site_url not set in mkdocs.yml; recommended for canonical URLs";
          else
            echo "Found $URL_LINE";
          fi

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "docs: publish site"

  noop-act:
    if: ${{ github.actor == 'nektos/act' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "[act] docs-publish skipped."
