name: legacy-scan

on:
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub CI images (e.g., 2025.10.03-a1b2c3d4 or v1.2.3). Falls back to repo variable CI_IMAGE_TAG or latest."
        required: false
        default: ""
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  guard:
    name: Require CI image tag (no drift)
    runs-on: ubuntu-latest
    outputs:
      is_act: ${{ steps.detect.outputs.is_act }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Enforce non-latest CI image tag
        shell: bash
        run: bash .github/scripts/guard-ci-image-tag.sh "${{ inputs.ci_image_tag }}"
      - name: Detect act runtime
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          if [ "${ACT:-}" = "true" ] || [ "${IS_ACT:-}" = "true" ]; then
            echo "Detected act environment"
            echo "is_act=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_act=false" >> "$GITHUB_OUTPUT"
          fi
  probe-ghcr:
    name: Probe GHCR access (ci-base)
    needs: guard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      can_pull: ${{ steps.probe.outputs.can_pull }}
    steps:
      - name: Try anonymous pull (ci-base)
        id: probe
        shell: bash
        run: |
          set -euo pipefail
          IMAGE_REF="ghcr.io/${{ github.repository_owner }}/ci-base:${{ (inputs.ci_image_tag != '' && inputs.ci_image_tag) || (vars.CI_IMAGE_TAG != '' && vars.CI_IMAGE_TAG) || '2025.10.03-f072ceb5' }}"
          echo "Probing anonymous pull for $IMAGE_REF"
          # If the image already exists locally, consider pullable without network
          if docker image inspect "$IMAGE_REF" >/dev/null 2>&1; then
            echo "Image present locally; skipping pull"
            echo "can_pull=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # Time-bound the pull to avoid hangs on problematic registries
          if command -v timeout >/dev/null 2>&1; then
            if timeout 120s docker pull "$IMAGE_REF"; then
              echo "can_pull=true" >> "$GITHUB_OUTPUT"
            else
              echo "can_pull=false" >> "$GITHUB_OUTPUT"
            fi
          else
            if docker pull "$IMAGE_REF"; then
              echo "can_pull=true" >> "$GITHUB_OUTPUT"
            else
              echo "can_pull=false" >> "$GITHUB_OUTPUT"
            fi
          fi

  legacy:
    name: Legacy violation[] scan
    needs: [guard, probe-ghcr]
    if: ${{ needs.probe-ghcr.outputs.can_pull == 'true' && needs.guard.outputs.is_act != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ${{ format('ghcr.io/{0}/ci-base:{1}', github.repository_owner, (inputs.ci_image_tag != '' && inputs.ci_image_tag) || (vars.CI_IMAGE_TAG != '' && vars.CI_IMAGE_TAG) || '2025.10.03-f072ceb5') }}
      options: --user 0:0
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Install deps (venv with baked deps)
        run: |
          bash .github/scripts/python-venv-install.sh
      - name: Run deny-usage scan (legacy violation[] enforcement)
        run: |
          . .venv/bin/activate
          python tools/deny_usage_scan.py

  legacy-fallback:
    name: Legacy violation[] scan (fallback, no container)
    needs: [guard, probe-ghcr]
    if: ${{ needs.probe-ghcr.outputs.can_pull != 'true' || needs.guard.outputs.is_act == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Setup Python venv
        shell: bash
        run: |
          set -euo pipefail
          python3 --version || true
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pyyaml
      - name: Run deny-usage scan (host)
        shell: bash
        run: |
          set -euo pipefail
          . .venv/bin/activate
          python tools/deny_usage_scan.py
