name: legacy-scan

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  legacy:
    name: Legacy violation[] scan
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/ci-base:latest
      options: --user 0:0
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Install deps (minimal)
        run: |
          python-venv-install
      - name: Run legacy scan
        run: |
          . .venv/bin/activate
          make legacy-scan
