name: link-audit

on:
  pull_request:
    paths:
      - "policies/**"
      - "tools/audit_links.py"
      - "tools/validate_links_baseline.py"
      - "links_audit_baseline.json"
      - ".github/workflows/link-audit.yml"
  push:
    branches: [main]
    paths:
      - "policies/**"
      - "tools/audit_links.py"
      - "tools/validate_links_baseline.py"
      - "links_audit_baseline.json"
      - ".github/workflows/link-audit.yml"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  audit:
    if: ${{ github.actor != 'nektos/act' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up Node.js
        if: ${{ github.actor != 'nektos/act' }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "20"
      - name: Set up Python
        if: ${{ github.actor != 'nektos/act' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.lock
            requirements.txt
      - name: Install deps (runtime)
        if: ${{ github.actor != 'nektos/act' }}
        run: |
          python -m pip install -U pip
          if [ -f requirements.lock ]; then pip install -r requirements.lock; else pip install -r requirements.txt; fi
      - name: Upload audit summary & baseline
        if: ${{ always() && github.actor != 'nektos/act' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: link-audit
          path: |
            link_audit_output.txt
            links_audit_baseline.json
