name: link-audit

on:
  pull_request:
    paths:
      - "policies/**"
      - "tools/audit_links.py"
      - "tools/validate_links_baseline.py"
      - "links_audit_baseline.json"
      - ".github/workflows/link-audit.yml"
  push:
    branches: [main]
    paths:
      - "policies/**"
      - "tools/audit_links.py"
      - "tools/validate_links_baseline.py"
      - "links_audit_baseline.json"
      - ".github/workflows/link-audit.yml"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/ci-base-rulehub:2025.10.02-a6909aab
      options: --user 0:0
    defaults:
      run:
        shell: bash
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Prepare Python env (venv with baked deps)
        run: |
          python-venv-install
      - name: Run link audit
        run: |
          . .venv/bin/activate
          set -euo pipefail
          # Generate current link audit report (JSON)
          python tools/analyze_links.py --export links_export.json --json links_audit_report.json
          # Compare against baseline; honors FAIL_LINK_AUDIT=1 to fail on drift
          python tools/compare_links_baseline.py | tee link_audit_output.txt
      - name: Upload audit summary & baseline
        if: ${{ always() && github.actor != 'nektos/act' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: link-audit
          path: |
            link_audit_output.txt
            links_audit_baseline.json
