name: Lint YAML

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write # for SARIF upload

jobs:
  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node (for Spectral linting)
        if: ${{ github.actor != 'nektos/act' }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "20"

      - name: Set up Python (with pip cache)
        if: ${{ github.actor != 'nektos/act' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.lock
            requirements.txt
            requirements-dev.lock
            requirements-dev.txt

      - name: Set up Python (act, no cache)
        if: ${{ github.actor == 'nektos/act' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      # setup-node already configured above; reuse for npx

      - name: Run Spectral (JSON->SARIF)
        if: ${{ github.actor != 'nektos/act' }}
        run: |
          # Use npx to run Spectral, output JSON to stdout and convert to SARIF
          npx --yes @stoplight/spectral lint --ruleset .spectral.yml --format json . \
            | python3 tools/convert_spectral_to_sarif.py - --output spectral.sarif || true
        continue-on-error: true

      - name: Upload Spectral SARIF artifact
        if: ${{ github.actor != 'nektos/act' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: spectral-sarif
          path: spectral.sarif
          if-no-files-found: ignore

      - name: Skip Spectral under act
        if: ${{ github.actor == 'nektos/act' }}
        run: echo "[act] Skipping Spectral (action dependency missing under local runner)"

  # plugin build removed: plugin has been moved to separate repository

  upload-sarif:
    name: Upload SARIF to code scanning
    if: ${{ github.actor != 'nektos/act' }}
    runs-on: ubuntu-latest
    needs: yamllint
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download Spectral SARIF artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          name: spectral-sarif
          path: .
      - name: Upload Spectral SARIF
        uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
        with:
          sarif_file: spectral.sarif
