name: Lint YAML

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  yamllint-gh:
    name: Lint YAML files (GitHub)
    if: ${{ github.actor != 'nektos/act' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node (for Spectral linting)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "20"
          # pinned commit to avoid drift

      - name: Set up Python (with pip cache)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.lock
            requirements.txt
            requirements-dev.lock
            requirements-dev.txt
          # pinned commit to avoid drift

      - name: Run Spectral (JSON->SARIF)
        run: |
          npx --yes @stoplight/spectral lint --ruleset .spectral.yml --format json . \
            | python3 tools/convert_spectral_to_sarif.py - --output spectral.sarif || true
        continue-on-error: true

      - name: Upload Spectral SARIF artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: spectral-sarif
          path: spectral.sarif
          if-no-files-found: ignore

  yamllint-act:
    name: Lint YAML files (act)
    if: ${{ github.actor == 'nektos/act' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Install yamllint (apt)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yamllint

      - name: Run yamllint (parsable)
        run: |
          yamllint . -f parsable

  upload-sarif:
    name: Upload SARIF to code scanning
    if: ${{ github.actor != 'nektos/act' }}
    runs-on: ubuntu-latest
    needs: yamllint-gh
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download Spectral SARIF artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: spectral-sarif
          path: .
      - name: Upload Spectral SARIF
        uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
        with:
          sarif_file: spectral.sarif
