name: Lint YAML

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub CI images (e.g., YYYY.MM.DD-<sha> or v1.2.3). Optional; falls back to repo/org CI_IMAGE_TAG or pinned fallback."
        required: false
        default: ""

permissions:
  contents: read
  security-events: write
  packages: read

jobs:
  guard:
    name: Require CI image tag (no drift)
    runs-on: ubuntu-latest
    env:
      CI_IMAGE_TAG: ${{ inputs.ci_image_tag != '' && inputs.ci_image_tag || vars.CI_IMAGE_TAG || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Enforce non-latest CI image tag
        shell: bash
        run: bash .github/scripts/guard-ci-image-tag.sh "${{ inputs.ci_image_tag }}"
  resolve:
    name: Resolve CI image (ci-base)
    runs-on: ubuntu-latest
    needs: guard
    env:
      CI_IMAGE_TAG: ${{ inputs.ci_image_tag != '' && inputs.ci_image_tag || vars.CI_IMAGE_TAG || '' }}
    outputs:
      image: ${{ steps.r.outputs.image }}
      tag: ${{ steps.r.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Resolve image
        id: r
        uses: ./.github/actions/resolve-ci-image
        with:
          ci_image_tag: ${{ inputs.ci_image_tag }}
          kind: base

  probe-ghcr:
    name: Probe GHCR access (ci-base)
    needs: [guard, resolve]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      can_pull: ${{ steps.probe.outputs.can_pull }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Try anonymous pull (ci-base)
        id: probe
        shell: bash
        run: |
          set -euo pipefail
          bash .github/scripts/ghcr-probe.sh "${{ needs.resolve.outputs.image }}"

  yamllint:
    name: Lint YAML files (Spectral + yamllint)
    needs: [guard, resolve, probe-ghcr]
    if: ${{ needs.probe-ghcr.outputs.can_pull == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.resolve.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Run yamllint (parsable)
        run: |
          yamllint . -f parsable

      - name: Run Spectral (JSON->SARIF)
        run: |
          bash .github/scripts/spectral-lint.sh --ruleset .spectral.yml --out spectral.sarif || true
        continue-on-error: true

  upload-sarif:
    name: Upload SARIF to code scanning
    if: ${{ github.actor != 'nektos/act' && needs.probe-ghcr.outputs.can_pull == 'true' }}
    runs-on: ubuntu-latest
    needs: [yamllint, resolve, probe-ghcr]
    permissions:
      contents: read
      security-events: write
    container:
      image: ${{ needs.resolve.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Recreate Spectral SARIF (JSON->SARIF)
        run: |
          bash .github/scripts/spectral-lint.sh --ruleset .spectral.yml --out spectral.sarif || true
        continue-on-error: true

      - name: Upload Spectral SARIF
        uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
        with:
          sarif_file: spectral.sarif

  yamllint-fallback:
    name: Lint YAML files (fallback, host)
    needs: [guard, resolve, probe-ghcr]
    if: ${{ needs.probe-ghcr.outputs.can_pull != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Setup Spectral (npx) and yamllint
        shell: bash
        run: |
          set -euo pipefail
          python3 -m pip install --user yamllint
          npm --version || true
      - name: Run yamllint (parsable)
        run: |
          ~/.local/bin/yamllint . -f parsable
      - name: Run Spectral (JSON->SARIF)
        run: |
          npx --yes @stoplight/spectral-cli@6.11.1 lint --ruleset .spectral.yml --format sarif --output spectral.sarif || true
        continue-on-error: true
      - name: Upload Spectral SARIF (host)
        if: ${{ github.actor != 'nektos/act' }}
        uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
        with:
          sarif_file: spectral.sarif
