name: opa-quick-check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub policy image (e.g., YYYY.MM.DD-<sha> or v1.2.3). Falls back to repo/org variable CI_IMAGE_TAG or the repository's pinned fallback."
        required: false
        default: ""

permissions:
  contents: read
  packages: read

jobs:
  guard:
    name: Require CI image tag (no drift)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Enforce non-latest CI image tag
        shell: bash
        run: bash .github/scripts/guard-ci-image-tag.sh "${{ inputs.ci_image_tag }}"
  resolve:
    name: Resolve CI image (ci-policy)
    needs: guard
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.r.outputs.image }}
      tag: ${{ steps.r.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Resolve image
        id: r
        uses: ./.github/actions/resolve-ci-image
        with:
          ci_image_tag: ${{ inputs.ci_image_tag }}
          kind: policy

  quick:
    name: OPA quick check
    runs-on: ubuntu-latest
    needs: [guard, resolve]
    container:
      image: "${{ needs.resolve.outputs.image }}"
      options: --user 0:0
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0

      - name: Parse & type check
        run: bash .github/scripts/opa-parse-typecheck.sh policies

      - name: Forbidden pattern scan
        run: bash .github/scripts/opa-forbidden-scan.sh policies

      - name: OPA fmt check
        run: bash .github/scripts/opa-fmt-check.sh policies

      - name: Summary
        if: always()
        run: |
          echo "OPA quick check complete"
          echo "::notice title=OPA Quick Check::Parse+Type, Forbidden Scan, Format OK"
