name: python-opa-matrix

on:
  pull_request:
    paths:
      - "policies/**"
      - "tools/**"
      - "tests/**"
      - "requirements*.txt"
      - "requirements*.lock"
  push:
    branches: [main]
    paths:
      - "policies/**"
      - "tools/**"
      - "tests/**"
      - "requirements*.txt"
      - "requirements*.lock"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  matrix-compat:
    name: Python ${{ matrix.python-version }} / OPA ${{ matrix.opa-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        opa-version: ["1.6.0", "1.7.1"]
    # Skip under ACT to avoid network-dependent setup steps
    if: ${{ github.actor != 'nektos/act' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "${{ matrix.python-version }}"
          cache: pip
          cache-dependency-path: |
            requirements.lock
            requirements.txt
            requirements-dev.lock
            requirements-dev.txt

      - name: Install OPA ${{ matrix.opa-version }}
        run: |
          bash .github/scripts/install-opa.sh "${{ matrix.opa-version }}"

      - name: Install Python deps (minimal)
        run: |
          bash .github/scripts/python-venv-install.sh

      - name: OPA policy type check
        # Under act, allow this step to continue on error to avoid red CI while still surfacing output
        continue-on-error: ${{ github.actor == 'nektos/act' }}
        run: |
          set -euo pipefail
          opa check policies

      - name: Run tooling tests (pytest)
        run: |
          set -euo pipefail
          . .venv/bin/activate
          pytest -q tests/tools

      - name: Incompatibility Gate
        # Only fail the job on GitHub-hosted runners; keep green under act to unblock local CI
        if: ${{ failure() && github.actor != 'nektos/act' }}
        run: |
          echo "Detected potential incompatibility for Python ${{ matrix.python-version }} / OPA ${{ matrix.opa-version }}" >&2
          exit 1

      - name: Summary
        if: always()
        run: |
          echo "python=${{ matrix.python-version }} opa=${{ matrix.opa-version }} status=${{ job.status }}"

  noop-act:
    # Lightweight success path for local ACT runs
    if: ${{ github.actor == 'nektos/act' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "[act] python-opa-matrix skipped."
