name: python-mypy

on:
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub CI images (e.g., 2025.10.03-a1b2c3d4 or v1.2.3). Falls back to repo variable CI_IMAGE_TAG or latest."
        required: false
        default: ""
  pull_request:
    paths:
      - "tools/**.py"
      - "mypy.ini"
      - ".github/workflows/python-mypy.yml"
  push:
    branches: [main, master]
    paths:
      - "tools/**.py"
      - "mypy.ini"
      - ".github/workflows/python-mypy.yml"

permissions:
  contents: read
  packages: read

jobs:
  guard:
    name: Require CI image tag (no drift)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Enforce non-latest CI image tag
        shell: bash
        run: bash .github/scripts/guard-ci-image-tag.sh "${{ inputs.ci_image_tag }}"
  mypy:
    needs: guard
    runs-on: ubuntu-latest
    env:
      ACT: "true"
    container:
      image: "ghcr.io/${{ github.repository_owner }}/ci-base:${{ inputs.ci_image_tag != '' && inputs.ci_image_tag || (vars.CI_IMAGE_TAG != '' && vars.CI_IMAGE_TAG || '2025.10.03-f072ceb5') }}"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user 0:0
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      # Python and mypy provided by CI container; install project deps using helper
      - name: Prepare environment (venv with baked deps)
        run: |
          bash .github/scripts/python-venv-install.sh
      - name: Run mypy
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -euo pipefail
          # Use mypy preinstalled in the CI image (/opt/ci-venv on PATH)
          export MYPY_CACHE_DIR=${MYPY_CACHE_DIR:-/tmp/mypy_cache}
          mkdir -p "$MYPY_CACHE_DIR"
          mypy --version || true
          mypy --config-file mypy.ini
