name: python-mypy

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "tools/**.py"
      - "mypy.ini"
      - ".github/workflows/python-mypy.yml"
  push:
    branches: [main, master]
    paths:
      - "tools/**.py"
      - "mypy.ini"
      - ".github/workflows/python-mypy.yml"

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      # Node not required; skip to avoid act runner action fetch issues
      - name: Skip Node setup under act
        if: ${{ github.actor == 'nektos/act' }}
        run: echo "Skipping Node setup under act"

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -U pip
          if [ -f requirements-dev.lock ]; then pip install -r requirements-dev.lock; else pip install -r requirements-dev.txt; fi
          pip install -r requirements.txt
          pip install mypy
      - name: Run mypy
        run: |
          . .venv/bin/activate
          mypy --install-types --non-interactive --config-file mypy.ini
