name: python-lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "tools/**.py"
      - "ruff.toml"
  push:
    branches: [main, master]
    paths:
      - "tools/**.py"
      - "ruff.toml"

permissions:
  contents: read
  security-events: write # needed for SARIF upload

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      # Node not required for ruff run itself; skip to save time

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.11-${{ hashFiles('requirements*.{txt,lock}') }}
          restore-keys: |
            venv-${{ runner.os }}-3.11-

      - name: Install ruff
        run: |
          if [ ! -d .venv ]; then python -m venv .venv; fi
          . .venv/bin/activate
          python -m pip install -U pip
          pip install ruff

      - name: Ruff check (tools/*.py) + SARIF
        run: |
          . .venv/bin/activate
          ruff check tools --output-format sarif | tee ruff.sarif
        continue-on-error: true # still upload SARIF even if failures

      # SARIF upload skipped for local act testing (API not available)
      # - name: Upload Ruff SARIF
      #   uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
      #   with:
      #     sarif_file: ruff.sarif
      #   if: ${{ always() && env.ACT != 'true' }}

      # - name: Upload Ruff SARIF
      #   uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
      #   with:
      #     sarif_file: ruff.sarif
      #   if: always()
