name: python-lint

on:
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub CI images (e.g., 2025.10.03-a1b2c3d4 or v1.2.3). Falls back to repo variable CI_IMAGE_TAG or latest."
        required: false
        default: ""
  pull_request:
    paths:
      - "tools/**.py"
      - "ruff.toml"
  push:
    branches: [main, master]
    paths:
      - "tools/**.py"
      - "ruff.toml"

permissions:
  contents: read
  security-events: write # needed for SARIF upload

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  guard:
    name: Require CI image tag (no drift)
    runs-on: ubuntu-latest
    steps:
      - name: Enforce non-latest CI image tag
        shell: bash
        run: |
          input_tag="${{ inputs.ci_image_tag }}"
          if [ "$input_tag" = "latest" ]; then
            echo "Workflow input ci_image_tag must not be 'latest'. Use an immutable tag (e.g., 2025.10.03-<sha> or vX.Y.Z)." >&2
            exit 1
          fi
          if [ -z "$input_tag" ]; then
            echo "Note: ci_image_tag input not provided. Ensure repository variable CI_IMAGE_TAG is set to a pinned tag to avoid drift." >&2
          fi

  ruff:
    needs: guard
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository_owner }}/ci-base:${{ inputs.ci_image_tag != '' && inputs.ci_image_tag || (vars.CI_IMAGE_TAG != '' && vars.CI_IMAGE_TAG || '2025.10.03-f072ceb5') }}"
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      # Node not required for ruff run itself; skip to save time

      - name: Ruff check (tools/*.py) + SARIF
        run: |
          ruff check tools --output-format sarif | tee ruff.sarif
        continue-on-error: true # still upload SARIF even if failures

      # SARIF upload skipped for local act testing (API not available)
      # - name: Upload Ruff SARIF
      #   uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
      #   with:
      #     sarif_file: ruff.sarif
      #   if: ${{ always() && env.ACT != 'true' }}

      # - name: Upload Ruff SARIF
      #   uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
      #   with:
      #     sarif_file: ruff.sarif
      #   if: always()
