name: python-mypy

on:
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub CI images (e.g., YYYY.MM.DD-<sha> or v1.2.3). Falls back to repo/org variable CI_IMAGE_TAG or the repository's pinned fallback."
        required: false
        default: ""
  pull_request:
    paths:
      - "tools/**.py"
      - "mypy.ini"
      - ".github/workflows/python-mypy.yml"
  push:
    branches: [main, master]
    paths:
      - "tools/**.py"
      - "mypy.ini"
      - ".github/workflows/python-mypy.yml"

permissions:
  contents: read
  packages: read

jobs:
  guard:
    name: Require CI image tag (no drift)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Enforce non-latest CI image tag
        shell: bash
        run: bash .github/scripts/guard-ci-image-tag.sh "${{ inputs.ci_image_tag }}"
  resolve:
    name: Resolve CI image
    needs: guard
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.resolve.outputs.image }}
      tag: ${{ steps.resolve.outputs.tag }}
    steps:
      - name: Resolve CI image tag and ref
        id: resolve
        uses: ./.github/actions/resolve-ci-image
        with:
          ci_image_tag: ${{ inputs.ci_image_tag }}
          kind: base
  mypy:
    needs: [guard, resolve]
    runs-on: ubuntu-latest
    env:
      ACT: "true"
    container:
      image: "${{ needs.resolve.outputs.image }}"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user 0:0
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      # Python and mypy provided by CI container; install project deps using helper
      - name: Prepare environment (venv with baked deps)
        run: |
          bash .github/scripts/python-venv-install.sh
      - name: Run mypy
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -euo pipefail
          # Use mypy preinstalled in the CI image (/opt/ci-venv on PATH)
          export MYPY_CACHE_DIR=${MYPY_CACHE_DIR:-/tmp/mypy_cache}
          mkdir -p "$MYPY_CACHE_DIR"
          mypy --version || true
          mypy --config-file mypy.ini
