name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      act_full:
        description: "Allow running under nektos/act (for local testing)."
        required: false
        default: "true"

permissions:
  contents: read

jobs:
  release:
    # Run only when manually dispatched with act_full=true and not under nektos/act.
    # This avoids failing under org policies that block Actions from creating PRs on push.
    if: ${{ github.actor != 'nektos/act' && github.event_name == 'workflow_dispatch' && inputs.act_full == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
