name: security-trivy (act-only)

on:
  # Prevent GitHub from running this workflow on push/PR; act will still run it with -W
  pull_request:
    branches-ignore:
      - "**"
  push:
    branches-ignore:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write # to upload SARIF

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-config-scan:
    name: Trivy IaC (config) scan
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'nektos/act' }}
    permissions:
      issues: write # to create/update PR comments
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Detect local/act or skip-supplychain mode
        id: env_flags
        run: |
          set -euo pipefail
          skip=false
          if [ "${ACT-}" = "true" ] || [ "${SKIP_SUPPLYCHAIN-}" = "1" ] || [ "${GITHUB_ACTOR-}" = "nektos/act" ]; then
            skip=true
          fi
          echo "skip_supplychain=${skip}" >> "$GITHUB_OUTPUT"

      - name: Trivy IaC via Docker (produce SARIF)
        if: ${{ steps.env_flags.outputs.skip_supplychain != 'true' }}
        id: trivy_iac
        env:
          TRIVY_VERSION: 0.56.2
          # Optional: set TRIVY_IMAGE_DIGEST to pin image immutably, e.g., sha256:...
          # TRIVY_IMAGE_DIGEST: ""
        run: bash .github/scripts/trivy-iac.sh

      - name: Create placeholder SARIF when supply-chain steps are skipped
        if: ${{ steps.env_flags.outputs.skip_supplychain == 'true' }}
        run: |
          echo '{}' > trivy-results.sarif

      - name: Summarize findings (Step Summary)
        if: always()
        run: |
          SUMMARY=$(node .github/scripts/trivy-summary.js trivy-results.sarif || echo "")
          if [ -n "$SUMMARY" ]; then
            {
              echo "${SUMMARY}";
            } >> "$GITHUB_STEP_SUMMARY"
          else
            echo "### Trivy IaC scan summary" >> "$GITHUB_STEP_SUMMARY"
            echo "- No SARIF or empty results" >> "$GITHUB_STEP_SUMMARY"
          fi
